import Foundation

/// Where MIDI generated by the patch goes, and where incoming MIDI is
/// read from. The real implementation is CoreMIDI virtual endpoints;
/// tests substitute a recorder.
///
/// Everything beyond the original note pair and `drainIncoming` has a
/// default no-op implementation in the protocol extension below, so
/// conformers that only care about notes keep compiling unchanged.
protocol MidiPort: AnyObject {
    func noteOn(channel: Int, note: Int, velocity: Int)
    func noteOff(channel: Int, note: Int)
    /// Drain incoming events since the last call.
    func drainIncoming() -> [MidiEvent]

    // Outgoing channel-voice messages.
    func controlChange(channel: Int, controller: Int, value: Int)
    func programChange(channel: Int, program: Int)
    /// 14-bit pitch bend, 0…16383 with 8192 = centre.
    func pitchBend(channel: Int, value: Int)
    func channelPressure(channel: Int, pressure: Int)

    // Outgoing system realtime / common messages (no channel).
    func clockTick()
    func clockStart()
    func clockStop()
    func clockContinue()
    /// Song position pointer, in MIDI beats (sixteenth notes), 0…16383.
    func songPosition(sixteenths: Int)
}

extension MidiPort {
    func controlChange(channel: Int, controller: Int, value: Int) {}
    func programChange(channel: Int, program: Int) {}
    func pitchBend(channel: Int, value: Int) {}
    func channelPressure(channel: Int, pressure: Int) {}
    func clockTick() {}
    func clockStart() {}
    func clockStop() {}
    func clockContinue() {}
    func songPosition(sixteenths: Int) {}
}

struct MidiEvent: Equatable, Sendable {
    enum Kind: Equatable, Sendable {
        case noteOn(velocity: Int)
        case noteOff
        case controlChange(controller: Int, value: Int)
        case programChange(program: Int)
        /// 14-bit value, 0…16383 with 8192 = centre.
        case pitchBend(value: Int)
        case channelPressure(pressure: Int)
        case clockTick, clockStart, clockStop, clockContinue
        case songPosition(sixteenths: Int)
    }

    /// 1…16 for channel-voice events; 0 for system messages.
    var channel: Int
    /// Meaningful for note events only; 0 otherwise.
    var note: Int
    var kind: Kind
}
