import Foundation

/// Where MIDI generated by the patch goes, and where incoming MIDI is
/// read from. The real implementation is CoreMIDI virtual endpoints;
/// tests substitute a recorder.
protocol MidiPort: AnyObject {
    func noteOn(channel: Int, note: Int, velocity: Int)
    func noteOff(channel: Int, note: Int)
    /// Drain incoming note events since the last call.
    func drainIncoming() -> [MidiEvent]
}

struct MidiEvent: Equatable, Sendable {
    enum Kind: Equatable, Sendable { case noteOn(velocity: Int), noteOff }
    var channel: Int
    var note: Int
    var kind: Kind
}
