import Foundation

/// Where MIDI generated by the patch goes, and where incoming MIDI is
/// read from. The real implementation is CoreMIDI virtual endpoints;
/// tests substitute a recorder.
protocol MidiPort: AnyObject {
    func noteOn(channel: Int, note: Int, velocity: Int)
    func noteOff(channel: Int, note: Int)
    /// Drain incoming note events since the last call.
    func drainIncoming() -> [MidiEvent]
}

struct MidiEvent: Equatable, Sendable {
    enum Kind: Equatable, Sendable { case noteOn(velocity: Int), noteOff }
    var channel: Int
    var note: Int
    var kind: Kind
}

/// Offline-renderable evaluation of a patch graph.
///
/// Semantics mirror the device where they are known and are documented
/// assumptions where they are not:
/// - Modules evaluate in list order per control block; a wire from a
///   later module reads its previous block's output (one-block delay),
///   which is how the pedal behaves for backward connections.
/// - CV inputs sum the incoming wires (× strength) on top of the param
///   value, clamped to 0…1. (Assumption: device sums rather than
///   replaces; calibrate against hardware later.)
/// - Pitch CV: fraction × 127 = MIDI note; Hz = 440 × 2^((n−69)/12).
///   (Assumption: matches the community 0…1 ≙ 0…127 mapping.)
/// - Sequencer: track 1 reads step values from params (verified against
///   factory patches); tracks 2+ live in saved_data whose layout is not
///   yet decoded — they output 0 and that limitation is deliberate.
final class PatchRuntime {
    struct Wire {
        var sourceNode: Int
        var sourceBlock: Int
        var destNode: Int
        var destBlock: Int
        var gain: Float
    }

    final class Node {
        let typeID: Int
        let options: [OptionValue]
        var params: [Float]
        /// Param block position → param array index.
        let paramIndexByPosition: [Int: Int]
        var cvOut: [Int: Float] = [:]
        var audioOut: [Int: [Float]] = [:]

        // Module state
        var phase: Double = 0
        var step: Int = 0
        var lastGate: Float = 0
        var lastRestart: Float = 0
        var finished = false
        var activeNote: Int = -1
        var heldNotes: [Int: Int] = [:]  // note → velocity, for midi in

        init(typeID: Int, options: [OptionValue], params: [Float],
             paramIndexByPosition: [Int: Int]) {
            self.typeID = typeID
            self.options = options
            self.params = params
            self.paramIndexByPosition = paramIndexByPosition
        }

        func optionText(_ index: Int) -> String {
            guard index < options.count, case .text(let t) = options[index] else { return "" }
            return t
        }
        func optionInt(_ index: Int) -> Int {
            guard index < options.count, case .number(let n) = options[index] else { return 0 }
            return Int(n)
        }
    }

    let sampleRate: Double
    private(set) var nodes: [Node] = []
    private var wires: [Wire] = []
    /// Wires grouped by (destNode, destBlock) for fast summing.
    private var wiresInto: [Int: [Wire]] = [:]
    weak var midi: MidiPort?

    @MainActor
    init(document: PatchDocument, sampleRate: Double) {
        self.sampleRate = sampleRate
        var indexOf: [UUID: Int] = [:]
        for (i, module) in document.modules.enumerated() {
            indexOf[module.id] = i
            let spec = document.catalog[module.typeID]
            let options = (try? spec.map {
                try BlockLayout.selectedOptions(spec: $0, optionBytes: module.optionBytes)
            }) ?? nil
            let paramBlocks = document.paramBlocks(of: module)
            var paramIndex: [Int: Int] = [:]
            for (i, block) in paramBlocks.enumerated() {
                if let position = block.position { paramIndex[position] = i }
            }
            nodes.append(Node(
                typeID: module.typeID,
                options: options ?? [],
                params: module.paramsRaw.map { Float($0) / 65535 },
                paramIndexByPosition: paramIndex))
        }
        for c in document.connections {
            guard let s = indexOf[c.sourceModule], let d = indexOf[c.destModule] else { continue }
            let wire = Wire(sourceNode: s, sourceBlock: c.sourceBlock,
                            destNode: d, destBlock: c.destBlock,
                            gain: Float(c.strengthRaw) / 10000)
            wires.append(wire)
            wiresInto[d << 8 | (c.destBlock & 0xFF), default: []].append(wire)
        }
    }

    // MARK: - Input helpers

    private func cvIn(node: Int, block: Int) -> Float {
        var value = nodes[node].paramIndexByPosition[block]
            .map { nodes[node].params[$0] } ?? 0
        for wire in wiresInto[node << 8 | (block & 0xFF)] ?? [] {
            value += (nodes[wire.sourceNode].cvOut[wire.sourceBlock] ?? 0) * wire.gain
        }
        return min(max(value, -1), 1)
    }

    private func audioIn(node: Int, block: Int, frames: Int) -> [Float] {
        var mix = [Float](repeating: 0, count: frames)
        for wire in wiresInto[node << 8 | (block & 0xFF)] ?? [] {
            guard let source = nodes[wire.sourceNode].audioOut[wire.sourceBlock] else { continue }
            for i in 0..<min(frames, source.count) {
                mix[i] += source[i] * wire.gain
            }
        }
        return mix
    }

    private static func pitchHz(_ cv: Float) -> Double {
        440 * pow(2, (Double(cv) * 127 - 69) / 12)
    }

    // MARK: - Render

    /// Renders one control block. `input` carries L/R capture buffers for
    /// Audio Input modules (may be empty), `output` receives the L/R mix.
    func render(frames: Int,
                inputL: [Float] = [], inputR: [Float] = [],
                outputL: inout [Float], outputR: inout [Float]) {
        for i in 0..<frames { outputL[i] = 0; outputR[i] = 0 }
        let incoming = midi?.drainIncoming() ?? []

        for index in nodes.indices {
            let node = nodes[index]
            switch node.typeID {
            case 1: renderAudioInput(node, inputL: inputL, inputR: inputR, frames: frames)
            case 2: renderAudioOutput(index, node, frames: frames, outputL: &outputL, outputR: &outputR)
            case 4: renderSequencer(index, node)
            case 5: renderLFO(index, node, frames: frames)
            case 7: renderVCA(index, node, frames: frames)
            case 14: renderOscillator(index, node, frames: frames)
            case 20: renderMidiNotesIn(node, events: incoming)
            case 60: renderMidiNoteOut(index, node)
            default:
                break  // Unimplemented modules are silent; cables read 0.
            }
        }
    }

    private func renderAudioInput(_ node: Node, inputL: [Float], inputR: [Float], frames: Int) {
        let silence = [Float](repeating: 0, count: frames)
        switch node.optionText(0) {
        case "left":
            node.audioOut[0] = inputL.count == frames ? inputL : silence
        case "right":
            node.audioOut[1] = inputR.count == frames ? inputR : silence
        default:
            node.audioOut[0] = inputL.count == frames ? inputL : silence
            node.audioOut[1] = inputR.count == frames ? inputR : silence
        }
    }

    private func renderAudioOutput(_ index: Int, _ node: Node, frames: Int,
                                   outputL: inout [Float], outputR: inout [Float]) {
        // gain_control option adds a gain cv block at position 2.
        let gain: Float = node.optionText(0) == "on" ? cvIn(node: index, block: 2) : 1
        let left = audioIn(node: index, block: 0, frames: frames)
        let right = audioIn(node: index, block: 1, frames: frames)
        switch node.optionText(1) {
        case "left":
            for i in 0..<frames { outputL[i] += left[i] * gain }
        case "right":
            for i in 0..<frames { outputR[i] += right[i] * gain }
        default:
            for i in 0..<frames {
                outputL[i] += left[i] * gain
                outputR[i] += right[i] * gain
            }
        }
    }

    private func renderSequencer(_ index: Int, _ node: Node) {
        let steps = max(node.optionInt(0), 1)
        let tracks = max(node.optionInt(1), 1)
        let gate = cvIn(node: index, block: 32)
        let restart = node.optionText(2) == "on" ? cvIn(node: index, block: 33) : 0

        if restart >= 0.5, node.lastRestart < 0.5 {
            node.step = 0
            node.finished = false
        }
        node.lastRestart = restart

        if gate >= 0.5, node.lastGate < 0.5, !node.finished {
            node.step += 1
            if node.step >= steps {
                if node.optionText(3) == "one_shot" {
                    node.step = steps - 1
                    node.finished = true
                } else {
                    node.step = 0
                }
            }
        }
        node.lastGate = gate

        // Track 1 = step params (device-verified). Tracks 2+ live in
        // saved_data, not yet decoded: they output 0.
        let stepValue = node.paramIndexByPosition[node.step]
            .map { node.params[$0] } ?? 0
        for track in 0..<tracks {
            node.cvOut[36 + track] = track == 0 ? stepValue : 0
        }
    }

    private func renderLFO(_ index: Int, _ node: Node, frames: Int) {
        // cv input mode: dial 0…1 sweeps ~0.05…25 Hz exponentially.
        // (Assumption; device curve not yet measured.)
        let control = cvIn(node: index, block: 0)
        let hz = 0.05 * pow(25 / 0.05, Double(control))
        node.phase += hz * Double(frames) / sampleRate
        node.phase -= node.phase.rounded(.down)

        let bipolar = node.optionText(2) == "-1 to 1"
        let raw: Double
        switch node.optionText(0) {
        case "sine": raw = (sin(node.phase * 2 * .pi) + 1) / 2
        case "triangle": raw = node.phase < 0.5 ? node.phase * 2 : 2 - node.phase * 2
        case "sawtooth": raw = 1 - node.phase
        case "ramp": raw = node.phase
        case "random": raw = node.phase < 0.02 ? Double.random(in: 0...1) : raw0(node)
        default: raw = node.phase < 0.5 ? 1 : 0  // square
        }
        node.cvOut[3] = Float(bipolar ? raw * 2 - 1 : raw)
    }

    private func raw0(_ node: Node) -> Double { Double(node.cvOut[3] ?? 0) }

    private func renderVCA(_ index: Int, _ node: Node, frames: Int) {
        let level = cvIn(node: index, block: 2)
        var left = audioIn(node: index, block: 0, frames: frames)
        for i in 0..<frames { left[i] *= level }
        node.audioOut[3] = left
        if node.optionText(0) == "stereo" {
            var right = audioIn(node: index, block: 1, frames: frames)
            for i in 0..<frames { right[i] *= level }
            node.audioOut[4] = right
        }
    }

    private func renderOscillator(_ index: Int, _ node: Node, frames: Int) {
        let hz = Self.pitchHz(cvIn(node: index, block: 0))
        let increment = hz / sampleRate
        var buffer = [Float](repeating: 0, count: frames)
        let waveform = node.optionText(0)
        for i in 0..<frames {
            let value: Double
            switch waveform {
            case "square": value = node.phase < 0.5 ? 1 : -1
            case "triangle": value = node.phase < 0.5 ? node.phase * 4 - 1 : 3 - node.phase * 4
            case "sawtooth": value = node.phase * 2 - 1
            default: value = sin(node.phase * 2 * .pi)  // sine
            }
            buffer[i] = Float(value)
            node.phase += increment
            if node.phase >= 1 { node.phase -= 1 }
        }
        node.audioOut[3] = buffer
    }

    private func renderMidiNotesIn(_ node: Node, events: [MidiEvent]) {
        let channel = node.optionInt(0)
        for event in events where event.channel == channel {
            switch event.kind {
            case .noteOn(let velocity) where velocity > 0:
                node.heldNotes[event.note] = velocity
                node.activeNote = event.note
            default:
                node.heldNotes[event.note] = nil
                if event.note == node.activeNote {
                    node.activeNote = node.heldNotes.keys.max() ?? -1
                }
            }
        }
        // Voice 1 blocks: note_out at position 0, gate_out at 1.
        if node.activeNote >= 0 {
            node.cvOut[0] = Float(node.activeNote) / 127
            node.cvOut[1] = 1
        } else {
            node.cvOut[1] = 0
        }
    }

    private func renderMidiNoteOut(_ index: Int, _ node: Node) {
        let channel = node.optionInt(0)
        let gate = cvIn(node: index, block: 1)
        if gate >= 0.5, node.lastGate < 0.5 {
            let note = Int((cvIn(node: index, block: 0) * 127).rounded())
            let velocity = node.optionText(1) == "on"
                ? max(Int((cvIn(node: index, block: 2) * 127).rounded()), 1)
                : 100
            if node.activeNote >= 0 { midi?.noteOff(channel: channel, note: node.activeNote) }
            midi?.noteOn(channel: channel, note: note, velocity: velocity)
            node.activeNote = note
        } else if gate < 0.5, node.lastGate >= 0.5, node.activeNote >= 0 {
            midi?.noteOff(channel: channel, note: node.activeNote)
            node.activeNote = -1
        }
        node.lastGate = gate
    }
}
